# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Solar Control
version: "1.2.21"
slug: solar-control
description: Solar Control add-on
url: "https://github.com/chrismelba/solar-control"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - share:rw
options:
  debug_level: "info"
schema:
  message: "str?"
  debug_level: "str?"
image: "ghcr.io/chrismelba/{arch}-addon-solar-control"
ports:
  8080/tcp: 8080
ingress: true
ingress_port: 8080
ingress_entry: /
homeassistant_api: true
# Add data persistence configuration
data: true
# Add Nginx configuration
webui: "http://[HOST]:[PORT:8080]/"
