# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Solar Control
version: "1.2.0"
slug: solar-control
description: Solar Control add-on
url: "https://github.com/chrismelba/solar-control"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
ports:
  8080/tcp: 8080
init: false
map:
  - share:rw
options:
  message: "Hello world..."
schema:
  message: "str?"
image: "ghcr.io/chrismelba/{arch}-addon-solar-control"
startup: application
boot: auto
webui: "http://[HOST]:[PORT:8080]"
watchdog: "http://[HOST]:[PORT:8080]/api/status"
ingress: true
ingress_port: 8080
ingress_entry: /
homeassistant_api: true
hassio_api: true
hassio_role: admin
services:
  - mqtt:need
  - hassio:need
