# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Solar Control
version: "1.2.11"
slug: solar-control
description: Solar Control add-on
url: "https://github.com/chrismelba/solar-control"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - share:rw
options:
  debug_level: "info"
schema:
  message: "str?"
  debug_level: "str?"
image: "ghcr.io/chrismelba/{arch}-addon-solar-control"
ports:
  8080/tcp: 8080
ingress: true
ingress_port: 8080
ingress_entry: /
homeassistant_api: true
# Add data persistence configuration
data: true
# Add Nginx configuration
webui: true
webui_config:
  server:
    listen: 8080
    server_name: localhost
    location:
      /:
        proxy_pass: http://localhost:8080
        proxy_set_header:
          Host: $host
          X-Real-IP: $remote_addr
          X-Forwarded-For: $proxy_add_x_forwarded_for
          X-Forwarded-Proto: $scheme