name: Build and Publish Add-on

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Build and Publish
        uses: docker/build-push-action@v6
        with:
          context: ./solar_control
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/aarch64-addon-solar-control:latest
            ghcr.io/${{ github.repository_owner }}/amd64-addon-solar-control:latest
            ghcr.io/${{ github.repository_owner }}/armhf-addon-solar-control:latest
            ghcr.io/${{ github.repository_owner }}/armv7-addon-solar-control:latest
            ghcr.io/${{ github.repository_owner }}/i386-addon-solar-control:latest
          platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6,linux/386
          build-args: |
            BUILD_FROM=ghcr.io/home-assistant/aarch64-base:3.15
            TEMPIO_VERSION=2021.09.0 